defaults:
  - dataset: local
  - model: ABMIL
  - settings: config.yaml
  - _self_

hydra:
  job:
    chdir: true
    config:
      override_dirname:
        exclude_keys:
          - seed
  sweep:
    dir: multirun
    subdir: ${model.name}/${hydra.job.override_dirname}/seed=${seed}

use_cuda: false
seed: 0
model_path: ${model.name}_${seed}.pth